name: Rcpsp.rs Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lib-Build:
    name: Build rcpsp library
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package rcpsp --all-features

      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1
        if: steps.check_permissions.outputs.has-permission
        with:
          args: --package rcpsp --all-features -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy manually without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --package rcpsp --all-features -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package rcpsp --all-features --release

  Scheduler-Build:
    name: Build scheduler binary
    runs-on: ubuntu-latest

    needs: Lib-Build

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package scheduler --all-features

      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1
        if: steps.check_permissions.outputs.has-permission
        with:
          args: --package rcpsp --all-features -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy manually without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --package rcpsp --all-features -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package scheduler --all-features --release
